// <auto-generated />
namespace Stock_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class innit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(innit));
        
        string IMigrationMetadata.Id
        {
            get { return "202307040305236_innit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
